-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE sapphirespamcleanse_trusted_user (
  trusted_user_id INT NOT NULL, trusted_user_timestamp TEXT DEFAULT '' NOT NULL,
  trusted_user_admin_id INT NOT NULL
);

CREATE UNIQUE INDEX trusted_user_id ON sapphirespamcleanse_trusted_user (trusted_user_id);
