-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/sapphirespamcleanse_trusted_user (
  trusted_user_id INT UNSIGNED NOT NULL,
  trusted_user_timestamp VARBINARY(14) DEFAULT '' NOT NULL,
  trusted_user_admin_id INT UNSIGNED NOT NULL,
  UNIQUE INDEX trusted_user_id (trusted_user_id)
) /*$wgDBTableOptions*/;
