-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/sapphirespamcleanse_trusted_user (
  trusted_user_id INTEGER UNSIGNED NOT NULL,
  trusted_user_timestamp BLOB DEFAULT '' NOT NULL,
  trusted_user_admin_id INTEGER UNSIGNED NOT NULL
);

CREATE UNIQUE INDEX trusted_user_id ON /*_*/sapphirespamcleanse_trusted_user (trusted_user_id);
